FROM public.ecr.aws/lambda/python:3.12

WORKDIR /app

ENV PYTHONPATH /app
ENV PATH="/app/bin:${PATH}"
RUN dnf install gcc -y
COPY requirements-full.txt ./requirements.txt
# RUN python -m pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt
COPY src src
