# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: ictlearningsciences
service: mentorpal-sbert

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-layers
custom:
  domain:
    dev: api-dev.mentorpal.org
    qa: api-qa.mentorpal.org
    prod: api.mentorpal.org
  customDomain:
    domainName: ${self:custom.domain.${opt:stage, 'dev'}}
    basePath: "sbert" # api root url becomes: api.pal3.org/llm-manager
    stage: ${self:provider.stage}
    endpointType: regional
    apiType: rest
    createRoute53Record: true
    securityPolicy: tls_1_2
    autoDomain: true
    preserveExternalPathMappings: true
  stages:
    offline:
      WEBACL_ARN: ${ssm:/shared-mentorpal/api_firewall_arn, ''}
    dev:  #TODO: replace with dedicated gaima key
      WEBACL_ARN: ${ssm:/shared-mentorpal/api_firewall_arn, ''}
    qa:
      WEBACL_ARN: ${ssm:/shared-mentorpal/api_firewall_arn, ''}
    prod:
      WEBACL_ARN: ${ssm:/shared-mentorpal/api_firewall_arn, ''}

#  serverless-layers requires a deployment bucket to be created before deploying this stack
  serverless-layers:
    - dependencies:
        layersDeploymentBucket: ${self:provider.deploymentBucket.name}
        dependenciesPath: ./requirements.txt
        compatibleRuntimes:
          - python3.12
        functions:
            - ping

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'offline'}
  deploymentBucket:
    name: '${self:service}-sls-deploy-${self:provider.stage}-v2'
    blockPublicAccess: true
    serverSideEncryption: AES256
    versioning: false
  environment:
    NUMBA_CACHE_DIR: /tmp
    EASYOCR_MODULE_PATH: /tmp
    MODULE_PATH: /tmp
package:
 patterns:
     - '!./node_modules'
     - '!./.venv'
     - '!./.serverless'
     - '!./infrastructure'
     - '!**/.mypy_cache/**'

functions:
  ping:
    handler: src/functions/ping.handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /ping
          method: get
          cors: true
  paraphrase:
    handler: src/functions/paraphrase.handler
    timeout: 120
    memorySize: 1024
    events:
      - http:
          path: /paraphrase
          method: post
          cors: true
  encode:
    handler: src/functions/encode.encode_handler
    timeout: 60
    memorySize: 1024
    events:
      - http:
          path: /encode
          method: post
          cors: true
          
  cosineSimilarityWeight:
    handler: src/functions/encode.cos_sim_weight_handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /cos_sim_weight
          method: get
          cors: true


resources:
  Conditions:
    AttachFirewall:
      Fn::Or:
        - Fn::Equals: ['${self:provider.stage}', 'dev']
        - Fn::Equals: ['${self:provider.stage}', 'qa']
        - Fn::Equals: ['${self:provider.stage}', 'prod']
  Resources:
    # TODO: Requires ALERT_SNS_ARN to be places in SSN
    # TrainDLQAlarm:
    #   Type: AWS::CloudWatch::Alarm
    #   Condition: CreateCloudWatchAlarm
    #   Properties:
    #     ActionsEnabled: true
    #     AlarmName: 'Number of failed train jobs ${self:resources.Resources.TrainDLQ.Properties.QueueName}'
    #     AlarmDescription: 'Number of failed train jobs greater than zero'
    #     Namespace: 'AWS/SQS'
    #     Statistic: 'Sum'
    #     MetricName: 'ApproximateNumberOfMessagesVisible'
    #     ComparisonOperator: 'GreaterThanThreshold'
    #     EvaluationPeriods: 1
    #     Period: 300 # 5 minutes in seconds
    #     Threshold: 0
    #     TreatMissingData: 'notBreaching'
    #     Dimensions:
    #       - Name: QueueName
    #         Value: ${self:resources.Resources.TrainDLQ.Properties.QueueName}
    #     AlarmActions:
    #       - ${self:custom.stages.${self:provider.stage}.ALERT_SNS_ARN}
    #     OKActions:
    #       - ${self:custom.stages.${self:provider.stage}.ALERT_SNS_ARN}

    # ApiErrors:
    #   Type: AWS::CloudWatch::Alarm
    #   Condition: CreateCloudWatchAlarm
    #   Properties:
    #     ActionsEnabled: true
    #     AlarmName: 'classifier API Gateway 5xx errors - ${self:provider.stage}'
    #     AlarmDescription: 'classifier API Gateway 5xx errors - ${self:provider.stage}'
    #     Namespace: AWS/ApiGateway
    #     MetricName: 5XXError
    #     Statistic: Sum
    #     Threshold: 0
    #     ComparisonOperator: 'GreaterThanThreshold'
    #     EvaluationPeriods: 1
    #     Period: 60
    #     TreatMissingData: 'notBreaching'
    #     Dimensions:
    #       - Name: ApiName
    #         Value: '${self:provider.stage}-${self:service}'
    #     AlarmActions:
    #       - ${self:custom.stages.${self:provider.stage}.ALERT_SNS_ARN}

    # this fails on first deploy because CloudFormation tries to create
    # association but the gateway does not yet exist
    # Workaround: Disable this resource on first deploy, when first deploy is successful, enable this resource and deploy again
    # FirewallAssociation:
    #   Type: AWS::WAFv2::WebACLAssociation
    #   Condition: AttachFirewall
    #   DependsOn: 'ApiGatewayRestApi'
    #   Properties:
    #     ResourceArn:
    #       Fn::Sub: 'arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGatewayRestApi}/stages/${self:provider.stage}'
    #     WebACLArn: '${self:custom.stages.${self:provider.stage}.WEBACL_ARN}'

    # configure cors for apigw error responses:
    Response5xx:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: 'method.request.header.origin'
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    Response4xx:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: 'method.request.header.origin'
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'